apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vpsie-autoscaler-controller
  labels:
    app.kubernetes.io/name: vpsie-autoscaler
    app.kubernetes.io/component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vpsie-autoscaler-controller
subjects:
- kind: ServiceAccount
  name: vpsie-autoscaler-controller
  namespace: vpsie-system
