apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vpsie-autoscaler-controller
  labels:
    app.kubernetes.io/name: vpsie-autoscaler
    app.kubernetes.io/component: controller
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vpsie-autoscaler
      app.kubernetes.io/component: controller
