apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vpsie-autoscaler
  labels:
    app.kubernetes.io/name: vpsie-autoscaler
    app.kubernetes.io/component: controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vpsie-autoscaler
      app.kubernetes.io/component: controller
  endpoints:
  - port: metrics
    interval: 30s
    scrapeTimeout: 10s
    path: /metrics
    scheme: http
